export const styles = {
    pageContainer: { padding: "120px 20px 40px", minHeight: "100vh", backgroundColor: "#f4f4f5", fontFamily: "sans-serif" },
    cardContainer: { maxWidth: 900, margin: "0 auto 30px", backgroundColor: "#ffffff", padding: "24px", border: "1px solid #d4d4d8" },
    headerRow: { display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "1px solid #e4e4e7", paddingBottom: 16, marginBottom: 24 },
    pageTitle: { fontSize: 24, margin: 0, color: "#18181b", fontWeight: "bold" },
    cancelBtn: { padding: "6px 12px", background: "#f4f4f5", border: "1px solid #d4d4d8", color: "#18181b", cursor: "pointer" },
    formContainer: { display: "flex", flexDirection: "column", gap: "20px" },
    sectionStyle: { padding: "20px", background: "#fafafa", border: "1px solid #e4e4e7", marginTop: "10px" },
    sectionHeading: { marginTop: 0, fontSize: 18, color: "#18181b", fontWeight: "bold", borderBottom: "1px solid #e4e4e7", paddingBottom: "10px", marginBottom: "16px" },
    gridContainer: { display: "grid", gap: 16 },
    flexRow: { display: "flex", gap: "16px" },
    flex1: { flex: 1 },
    labelStyle: { display: "block", fontWeight: "bold", marginBottom: 6, fontSize: 13, color: "#3f3f46" },
    inputStyle: { width: "100%", padding: "8px", border: "1px solid #d4d4d8", fontSize: 14, boxSizing: "border-box", backgroundColor: "#fff", color: "#18181b" },
    awardCheckboxLabel: { display: "flex", alignItems: "center", gap: "8px", fontWeight: "bold", cursor: "pointer", fontSize: 14, color: "#18181b" },
    checkbox: { width: 16, height: 16 },
    awardFields: { display: "flex", flexDirection: "column", gap: "16px", marginTop: "16px", paddingLeft: "24px", borderLeft: "2px solid #e4e4e7" },
    submitBtn: { padding: "12px", color: "white", border: "none", fontSize: "15px", fontWeight: "bold", cursor: "pointer", backgroundColor: "#27272a" },
    existingProjectsTitle: { fontSize: 20, margin: "0 0 20px 0", color: "#18181b", fontWeight: "bold" },
    projectListContainer: { display: "flex", flexDirection: "column", gap: "8px" },
    projectListItem: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px", background: "#ffffff", border: "1px solid #e4e4e7" },
    projectIcon: { fontSize: "20px", background: "#f4f4f5", padding: "4px", border: "1px solid #e4e4e7", width: "32px", height: "32px", display: "flex", justifyContent: "center", alignItems: "center" },
    projectTitleText: { fontWeight: "bold", color: "#18181b" },
    projectCategoryText: { fontSize: 12, color: "#71717a", marginTop: "2px" },
    editBtn: { padding: "4px 10px", background: "#fff", border: "1px solid #d4d4d8", color: "#18181b", cursor: "pointer", fontSize: 13 },
    deleteBtn: { padding: "4px 10px", background: "#fff", border: "1px solid #fca5a5", color: "#ef4444", cursor: "pointer", fontSize: 13 }
};
