export const styles = {
    pageContainer: { paddingTop: 80, paddingBottom: 60, minHeight: "100vh", backgroundColor: "transparent" },
    cardContainer: { maxWidth: 800, margin: "0 auto 40px", backgroundColor: "rgba(255, 255, 255, 0.9)", backdropFilter: "blur(16px)", padding: "32px", borderRadius: "24px", boxShadow: "0 24px 64px rgba(13,110,253,0.15), 0 8px 24px rgba(13,110,253,0.05)" },
    headerRow: { display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "2px solid #eef3ff", paddingBottom: 16, marginBottom: 24 },
    pageTitle: { fontFamily: "'Poppins', sans-serif", fontSize: 24, margin: 0, color: "#0d1b2a" },
    cancelBtn: { padding: "6px 12px", background: "#f3f4f6", border: "none", borderRadius: "6px", cursor: "pointer" },
    formContainer: { display: "flex", flexDirection: "column", gap: "20px" },
    sectionStyle: { padding: "20px", background: "rgba(248, 251, 255, 0.6)", border: "1px solid rgba(238, 243, 255, 0.5)", borderRadius: "16px", marginTop: "10px" },
    sectionHeading: { marginTop: 0 },
    gridContainer: { display: "grid", gap: 16 },
    flexRow: { display: "flex", gap: "16px" },
    flex1: { flex: 1 },
    labelStyle: { display: "block", fontWeight: "bold", marginBottom: 6, fontSize: 14, color: "#333", fontFamily: "'Poppins', sans-serif" },
    inputStyle: { width: "100%", padding: "10px", borderRadius: "6px", border: "1px solid #ccc", fontSize: 14, fontFamily: "'Poppins', sans-serif", boxSizing: "border-box" },
    awardCheckboxLabel: { display: "flex", alignItems: "center", gap: "8px", fontWeight: "bold", cursor: "pointer" },
    checkbox: { width: 18, height: 18 },
    awardFields: { display: "flex", flexDirection: "column", gap: "16px", marginTop: "16px" },
    submitBtn: { padding: "14px", color: "white", border: "none", borderRadius: "8px", fontSize: "16px", fontWeight: "bold", cursor: "pointer" },
    existingProjectsTitle: { fontFamily: "'Poppins', sans-serif", fontSize: 20, margin: "0 0 20px 0" },
    projectListContainer: { display: "flex", flexDirection: "column", gap: "12px" },
    projectListItem: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px", background: "#f8fbff", border: "1px solid #eef3ff", borderRadius: "10px" },
    projectIcon: { fontSize: "28px" },
    projectTitleText: { fontWeight: 700 },
    projectCategoryText: { fontSize: 12, color: "#5a7a9a" },
    editBtn: { padding: "6px 12px", background: "#e0f2fe", border: "none", borderRadius: "6px", cursor: "pointer" },
    deleteBtn: { padding: "6px 12px", background: "#fee2e2", color: "red", border: "none", borderRadius: "6px", cursor: "pointer" }
};
