export const styles = {
    nav: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 1000,
        padding: "0 32px",
        height: 64,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        background: "rgba(255,255,255,0.6)",
        backdropFilter: "blur(20px)",
        WebkitBackdropFilter: "blur(20px)",
        borderBottom: "1px solid rgba(163,216,244,0.25)",
        boxShadow: "0 2px 20px rgba(13,110,253,0.07)",
    },
    leftContainer: { display: "flex", alignItems: "center", flex: 1 },
    logoContainer: { display: "flex", alignItems: "center", justifyContent: "center", flex: 1 },
    logoText: {
        fontFamily: "'Poppins', sans-serif",
        fontWeight: 800,
        fontSize: 22,
        background: "linear-gradient(135deg,#0D6EFD,#A3D8F4)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        letterSpacing: "-0.5px"
    },
    cheerButton: {
        padding: "6px 14px",
        borderRadius: 50,
        background: "linear-gradient(135deg,#ffc8d5,#A3D8F4)",
        border: "none",
        cursor: "pointer",
        fontFamily: "'Poppins',sans-serif",
        fontWeight: 600,
        fontSize: 12,
        color: "#1a2a4a",
        boxShadow: "0 2px 8px rgba(163,216,244,0.4)",
    },
    navLinksContainer: { display: "flex", alignItems: "center", gap: 12, flex: 1, justifyContent: "flex-end" },
    navLink: {
        padding: "7px 16px",
        borderRadius: 50,
        border: "none",
        cursor: "pointer",
        fontFamily: "'Poppins',sans-serif",
        fontWeight: 600,
        fontSize: 13,
        transition: "all 0.2s",
    },
    chatButton: {
        width: 38,
        height: 38,
        borderRadius: "50%",
        border: "none",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
};
