export const styles = {
    loadingContainer: { minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: "#0D6EFD" },
    loadingText: { marginTop: 16, fontFamily: "'Poppins',sans-serif", fontWeight: 600 },
    pageContainer: { paddingTop: 64, minHeight: "100vh", position: "relative" },
    filterContainer: { padding: "24px 48px 16px", display: "flex", flexWrap: "wrap", gap: 10, maxWidth: 1440, margin: "0 auto", alignItems: "center" },
    searchBarWrap: { flex: "1 1 min-content", minWidth: 200, position: "relative", display: "flex", alignItems: "center" },
    searchIcon: { position: "absolute", left: 16, color: "#8aabcc" },
    searchInput: { width: "100%", padding: "10px 16px 10px 44px", borderRadius: 50, border: "1px solid #e2e8f0", fontFamily: "'Poppins',sans-serif", fontSize: 14, outline: "none", transition: "all 0.2s", background: "white", color: "#0d1b2a" },
    filterTab: { padding: "8px 20px", borderRadius: 50, border: "none", cursor: "pointer", fontFamily: "'Poppins',sans-serif", fontWeight: 600, fontSize: 13, transition: "all 0.2s" },
    mainContentWrapper: { maxWidth: 1440, margin: "0 auto", paddingBottom: 80 },
    selectionSection: { padding: "0 48px", marginBottom: 32 },
    selectionCardOuter: { background: "rgba(255, 255, 255, 0.6)", backdropFilter: "blur(24px)", borderRadius: 24, padding: "24px 0", boxShadow: "0 24px 64px rgba(13,110,253,0.15), 0 8px 24px rgba(13,110,253,0.05)", border: "1px solid rgba(255,255,255,0.6)" },
    selectionHeading: { padding: "0 24px", marginBottom: 16, fontFamily: "'Poppins',sans-serif", fontWeight: 700, fontSize: 18, color: "#0d1b2a" },
    noProjectsText: { padding: "20px 24px", textAlign: "center", color: "#8aabcc" },
    scrollRow: { display: "flex", gap: 20, overflowX: "auto", padding: "10px 24px 16px", scrollbarWidth: "none", userSelect: "none" },
    scrollHintWrap: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 4, color: "#8aabcc", fontSize: 13, fontFamily: "'Poppins',sans-serif" },
    projectMiniCard: { flex: "0 0 300px", scrollSnapAlign: "center", borderRadius: 16, background: "rgba(255, 255, 255, 0.8)", display: "flex", alignItems: "center", gap: 16, padding: 16, position: "relative" },
    awardBadge: { position: "absolute", top: -1, right: -1, background: "linear-gradient(135deg, #FFDF40, #FFC107)", color: "#855E00", padding: "4px 12px", borderRadius: "0 16px 0 12px", fontSize: 10, fontWeight: 800, fontFamily: "'Poppins',sans-serif", display: "flex", alignItems: "center", gap: 4, zIndex: 10, boxShadow: "0 4px 12px rgba(255,193,7,0.4)", border: "none" },
    recommendedBadge: { position: "absolute", top: -1, right: -1, background: "linear-gradient(135deg, #6EE7B7, #34D399)", color: "#064E3B", padding: "4px 12px", borderRadius: "0 16px 0 12px", fontSize: 10, fontWeight: 800, fontFamily: "'Poppins',sans-serif", display: "flex", alignItems: "center", gap: 4, zIndex: 10, boxShadow: "0 4px 12px rgba(52,211,153,0.4)", border: "none" },
    projectIconBadge: { width: 64, height: 64, flexShrink: 0, borderRadius: 12, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28 },
    overflowHidden: { overflow: "hidden" },
    projectMiniTitle: { fontFamily: "'Poppins',sans-serif", fontWeight: 700, fontSize: 15, color: "#0d1b2a", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
    projectMiniCategory: { fontFamily: "'Poppins',sans-serif", fontSize: 12, color: "#8aabcc", fontWeight: 500, marginTop: 4 },
    detailsOuterContainer: { padding: "0 48px" },
    detailsMainCard: { background: "rgba(255, 255, 255, 0.6)", backdropFilter: "blur(24px)", borderRadius: 24, boxShadow: "0 24px 64px rgba(13,110,253,0.15), 0 8px 24px rgba(13,110,253,0.05)", overflow: "hidden", border: "1px solid rgba(255,255,255,0.6)" },
    coverHeader: { height: 350, display: "flex", alignItems: "center", justifyContent: "center", position: "relative" },
    playVideoButton: { width: 72, height: 72, borderRadius: "50%", background: "rgba(255,255,255,0.9)", backdropFilter: "blur(8px)", display: "flex", alignItems: "center", justifyContent: "center", color: "#0D6EFD", boxShadow: "0 8px 32px rgba(0,0,0,0.15)" },
    playIconMargin: { marginLeft: 4 },
    navLeftArrow: { position: "absolute", left: 24, width: 44, height: 44, borderRadius: "50%", background: "rgba(255,255,255,0.9)", backdropFilter: "blur(4px)", border: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 2px 10px rgba(0,0,0,0.1)", color: "#0D6EFD" },
    navRightArrow: { position: "absolute", right: 24, width: 44, height: 44, borderRadius: "50%", background: "rgba(255,255,255,0.9)", backdropFilter: "blur(4px)", border: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 2px 10px rgba(0,0,0,0.1)", color: "#0D6EFD" },
    detailsPadding: { padding: "40px 48px" },
    titleSection: { marginBottom: 32 },
    mainTitle: { fontFamily: "'Poppins',sans-serif", fontWeight: 800, fontSize: 32, color: "#0d1b2a", margin: "0 0 8px 0" },
    metaData: { fontFamily: "'Poppins',sans-serif", fontSize: 14, color: "#8aabcc", fontWeight: 600, marginBottom: 20 },
    mainDesc: { fontFamily: "'Poppins',sans-serif", color: "#5a7a9a", fontSize: 16, lineHeight: 1.8, maxWidth: 900 },
    infoBlock: { background: "rgba(248, 251, 255, 0.6)", borderRadius: 20, padding: 28, border: "1px solid rgba(238, 243, 255, 0.5)" },
    flexColGap24: { display: "flex", flexDirection: "column", gap: 24 },
    grid2Col: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 32 },
    subHeadingStyle: { fontFamily: "'Poppins',sans-serif", fontWeight: 700, fontSize: 18, color: "#0d1b2a", marginBottom: 16, display: "flex", alignItems: "center", gap: 8 },
    textStyle: { fontFamily: "'Poppins',sans-serif", color: "#5a7a9a", fontSize: 14, lineHeight: 1.8, margin: 0 },
    techFeatureGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 24, marginBottom: 32 },
    roleSection: { marginBottom: 24 },
    roleText: { fontFamily: "'Poppins',sans-serif", fontWeight: 600, color: "#4a6a8a", fontSize: 14 },
    tagWrap: { display: "flex", flexWrap: "wrap", gap: 8 },
    techTag: { padding: "6px 14px", borderRadius: 50, background: "rgba(13,110,253,0.1)", border: "1px solid rgba(13,110,253,0.2)", fontFamily: "'Poppins',sans-serif", fontWeight: 600, fontSize: 12, color: "#0D6EFD" },
    toolTag: { padding: "6px 14px", borderRadius: 50, background: "#f1f5f9", border: "1px solid #e2e8f0", fontFamily: "'Poppins',sans-serif", fontWeight: 600, fontSize: 12, color: "#475569" },
    featureList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 14 },
    featureItem: { fontFamily: "'Poppins',sans-serif", fontSize: 14, color: "#5a7a9a", display: "flex", alignItems: "flex-start", gap: 10 },
    featureCheck: { marginTop: 2, color: "#10b981" },
    featureTextLine: { lineHeight: 1.6 },
    resultLearningGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 24, marginBottom: 48 },
    gallerySection: { marginBottom: 48 },
    galleryGrid: { display: "grid", gap: 8, borderRadius: 16, overflow: "hidden" },
    galleryLargeItem: { cursor: "pointer", overflow: "hidden" },
    gallerySmallItem: { height: 250, cursor: "pointer", position: "relative", overflow: "hidden" },
    galleryImage: { width: "100%", height: "100%", objectFit: "cover", transition: "transform 0.3s" },
    galleryOverlay: { position: "absolute", inset: 0, background: "rgba(0,0,0,0.5)", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontSize: 36, fontWeight: 800, fontFamily: "'Poppins',sans-serif" },
    awardSection: { marginBottom: 48, background: "linear-gradient(135deg, rgba(255, 252, 240, 0.15) 0%, rgba(255, 249, 230, 0.15) 100%)", backdropFilter: "blur(16px)", borderRadius: 20, border: "1px solid rgba(255, 229, 143, 0.4)", padding: 32, display: "flex", flexWrap: "wrap", gap: 32, alignItems: "center" },
    awardTextSide: { flex: "1 1 300px" },
    awardLabelTag: { display: "inline-flex", alignItems: "center", gap: 8, background: "linear-gradient(135deg, #FFDF40, #FFC107)", color: "#855E00", padding: "6px 14px", borderRadius: 50, fontSize: 12, fontWeight: 700, fontFamily: "'Poppins',sans-serif", marginBottom: 16, boxShadow: "0 4px 12px rgba(255,193,7,0.3)", border: "none" },
    recommendedLabelTag: { display: "inline-flex", alignItems: "center", gap: 8, background: "linear-gradient(135deg, #6EE7B7, #34D399)", color: "#064E3B", padding: "6px 14px", borderRadius: 50, fontSize: 12, fontWeight: 700, fontFamily: "'Poppins',sans-serif", marginBottom: 16, boxShadow: "0 4px 12px rgba(52,211,153,0.3)", border: "none" },
    awardTitle: { fontFamily: "'Poppins',sans-serif", fontWeight: 800, fontSize: 22, color: "#874d00", margin: "0 0 8px 0" },
    awardComp: { fontFamily: "'Poppins',sans-serif", fontSize: 13, color: "#ad6800", fontWeight: 600, marginBottom: 12 },
    awardDesc: { fontFamily: "'Poppins',sans-serif", color: "#874d00", fontSize: 14, lineHeight: 1.7, opacity: 0.9 },
    awardImageSide: { flex: "0 0 240px", height: 160, borderRadius: 16, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: "#d48806", boxShadow: "0 8px 24px rgba(250, 173, 20, 0.2)", position: "relative", overflow: "hidden" },
    coverImage: { width: "100%", height: "100%", objectFit: "cover" },
    placeholderIcon: { marginBottom: 8, opacity: 0.5 },
    placeholderText: { fontFamily: "'Poppins',sans-serif", fontSize: 12, fontWeight: 600 },
    footerRow: { display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 32 },
    langBarWrap: { flex: "1 1 350px" },
    langTitle: { fontFamily: "'Poppins',sans-serif", fontWeight: 700, fontSize: 16, color: "#0d1b2a", margin: "0 0 12px 0" },
    langBarTrack: { height: 10, borderRadius: 10, display: "flex", overflow: "hidden", marginBottom: 12, background: "#eef3ff" },
    langLegendWrap: { display: "flex", flexWrap: "wrap", gap: 16 },
    langLegendItem: { display: "flex", alignItems: "center", gap: 6, fontFamily: "'Poppins',sans-serif", fontSize: 12, color: "#5a7a9a", fontWeight: 500 },
    langPercent: { color: "#8aabcc" },
    noLangText: { fontSize: 13, color: "#8aabcc" },
    actionBtnsWrap: { display: "flex", gap: 12 },
    liveBtn: { padding: "12px 24px", borderRadius: 10, background: "#0D6EFD", color: "white", textDecoration: "none", display: "flex", alignItems: "center", gap: 8, fontFamily: "'Poppins',sans-serif", fontWeight: 700, fontSize: 13, boxShadow: "0 4px 12px rgba(13,110,253,0.2)" },
    githubBtn: { padding: "12px 24px", borderRadius: 10, background: "#f0f6ff", color: "#0D6EFD", border: "1px solid #d0e8ff", textDecoration: "none", display: "flex", alignItems: "center", gap: 8, fontFamily: "'Poppins',sans-serif", fontWeight: 700, fontSize: 13 },
    lightboxOverlay: { position: "fixed", inset: 0, zIndex: 9999, background: "rgba(0,0,0,0.9)", display: "flex", alignItems: "center", justifyContent: "center" },
    lightboxClose: { position: "absolute", top: 24, right: 24, color: "white", cursor: "pointer", zIndex: 10000 },
    lightboxLeftBtn: { position: "absolute", left: 24, width: 50, height: 50, borderRadius: "50%", background: "rgba(255,255,255,0.1)", border: "none", color: "white", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 10000 },
    lightboxRightBtn: { position: "absolute", right: 24, width: 50, height: 50, borderRadius: "50%", background: "rgba(255,255,255,0.1)", border: "none", color: "white", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 10000 },
    lightboxCounter: { position: "absolute", bottom: 24, color: "white", fontFamily: "'Poppins',sans-serif", fontSize: 14, letterSpacing: 2 },
    lightboxContent: { maxWidth: "90vw", maxHeight: "85vh", display: "flex", justifyContent: "center", alignItems: "center" },
    lightboxImage: { maxWidth: "100%", maxHeight: "85vh", objectFit: "contain", borderRadius: 8 },
    lightboxVideo: { width: "80vw", height: "70vh", border: "none", borderRadius: 16, backgroundColor: "black" }
};
