-- ============================================================================
-- Migration: Separate Projects Table & Remove image_icon Column
-- ============================================================================

-- 1. Create achievements table
CREATE TABLE IF NOT EXISTS public.achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Achievement',
  description TEXT,
  year TEXT,
  link_url TEXT,
  github_url TEXT,
  my_role TEXT,
  problem TEXT,
  solution TEXT,
  results_impact TEXT,
  key_learnings TEXT,
  tags TEXT[],
  tools TEXT[],
  features TEXT[],
  languages JSONB,
  video_url TEXT,
  gallery TEXT[],
  award JSONB,
  is_recommended BOOLEAN DEFAULT FALSE,
  sort_order INT DEFAULT 0,
  is_hidden BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create activities table
CREATE TABLE IF NOT EXISTS public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Activity',
  description TEXT,
  year TEXT,
  link_url TEXT,
  github_url TEXT,
  my_role TEXT,
  problem TEXT,
  solution TEXT,
  results_impact TEXT,
  key_learnings TEXT,
  tags TEXT[],
  tools TEXT[],
  features TEXT[],
  languages JSONB,
  video_url TEXT,
  gallery TEXT[],
  award JSONB,
  is_recommended BOOLEAN DEFAULT FALSE,
  sort_order INT DEFAULT 0,
  is_hidden BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create experiences table
CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Experience',
  description TEXT,
  year TEXT,
  link_url TEXT,
  github_url TEXT,
  company TEXT,
  my_role TEXT,
  problem TEXT,
  solution TEXT,
  results_impact TEXT,
  key_learnings TEXT,
  tags TEXT[],
  tools TEXT[],
  features TEXT[],
  languages JSONB,
  video_url TEXT,
  gallery TEXT[],
  award JSONB,
  is_recommended BOOLEAN DEFAULT FALSE,
  sort_order INT DEFAULT 0,
  is_hidden BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Migrate existing data from projects table safely checking column existence
DO $$
DECLARE
  has_sort_order BOOLEAN;
  has_is_hidden BOOLEAN;
  has_is_recommended BOOLEAN;
  has_github_url BOOLEAN;
  has_my_role BOOLEAN;
  has_problem BOOLEAN;
  has_solution BOOLEAN;
  has_results_impact BOOLEAN;
  has_key_learnings BOOLEAN;
  has_tags BOOLEAN;
  has_tools BOOLEAN;
  has_features BOOLEAN;
  has_languages BOOLEAN;
  has_video_url BOOLEAN;
  has_gallery BOOLEAN;
  has_award BOOLEAN;
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'projects') THEN
    
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'sort_order') INTO has_sort_order;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'is_hidden') INTO has_is_hidden;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'is_recommended') INTO has_is_recommended;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'github_url') INTO has_github_url;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'my_role') INTO has_my_role;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'problem') INTO has_problem;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'solution') INTO has_solution;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'results_impact') INTO has_results_impact;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'key_learnings') INTO has_key_learnings;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'tags') INTO has_tags;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'tools') INTO has_tools;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'features') INTO has_features;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'languages') INTO has_languages;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'video_url') INTO has_video_url;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'gallery') INTO has_gallery;
    SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'award') INTO has_award;

    -- Migrate Achievements
    EXECUTE 'INSERT INTO public.achievements (title, category, description, year, link_url, github_url, my_role, problem, solution, results_impact, key_learnings, tags, tools, features, languages, video_url, gallery, award, is_recommended, sort_order, is_hidden, created_at)
      SELECT title, ''Achievement'', description, year, link_url, '
      || CASE WHEN has_github_url THEN 'github_url' ELSE 'NULL' END || ', '
      || CASE WHEN has_my_role THEN 'my_role' ELSE 'NULL' END || ', '
      || CASE WHEN has_problem THEN 'problem' ELSE 'NULL' END || ', '
      || CASE WHEN has_solution THEN 'solution' ELSE 'NULL' END || ', '
      || CASE WHEN has_results_impact THEN 'results_impact' ELSE 'NULL' END || ', '
      || CASE WHEN has_key_learnings THEN 'key_learnings' ELSE 'NULL' END || ', '
      || CASE WHEN has_tags THEN 'tags' ELSE 'NULL' END || ', '
      || CASE WHEN has_tools THEN 'tools' ELSE 'NULL' END || ', '
      || CASE WHEN has_features THEN 'features' ELSE 'NULL' END || ', '
      || CASE WHEN has_languages THEN 'languages' ELSE 'NULL' END || ', '
      || CASE WHEN has_video_url THEN 'video_url' ELSE 'NULL' END || ', '
      || CASE WHEN has_gallery THEN 'gallery' ELSE 'NULL' END || ', '
      || CASE WHEN has_award THEN 'award' ELSE 'NULL' END || ', '
      || CASE WHEN has_is_recommended THEN 'COALESCE(is_recommended, FALSE)' ELSE 'FALSE' END || ', '
      || CASE WHEN has_sort_order THEN 'COALESCE(sort_order, 0)' ELSE '0' END || ', '
      || CASE WHEN has_is_hidden THEN 'COALESCE(is_hidden, FALSE)' ELSE 'FALSE' END || ', created_at
      FROM public.projects WHERE category = ''Achievement''
      ON CONFLICT DO NOTHING';

    -- Migrate Activities
    EXECUTE 'INSERT INTO public.activities (title, category, description, year, link_url, github_url, my_role, problem, solution, results_impact, key_learnings, tags, tools, features, languages, video_url, gallery, award, is_recommended, sort_order, is_hidden, created_at)
      SELECT title, ''Activity'', description, year, link_url, '
      || CASE WHEN has_github_url THEN 'github_url' ELSE 'NULL' END || ', '
      || CASE WHEN has_my_role THEN 'my_role' ELSE 'NULL' END || ', '
      || CASE WHEN has_problem THEN 'problem' ELSE 'NULL' END || ', '
      || CASE WHEN has_solution THEN 'solution' ELSE 'NULL' END || ', '
      || CASE WHEN has_results_impact THEN 'results_impact' ELSE 'NULL' END || ', '
      || CASE WHEN has_key_learnings THEN 'key_learnings' ELSE 'NULL' END || ', '
      || CASE WHEN has_tags THEN 'tags' ELSE 'NULL' END || ', '
      || CASE WHEN has_tools THEN 'tools' ELSE 'NULL' END || ', '
      || CASE WHEN has_features THEN 'features' ELSE 'NULL' END || ', '
      || CASE WHEN has_languages THEN 'languages' ELSE 'NULL' END || ', '
      || CASE WHEN has_video_url THEN 'video_url' ELSE 'NULL' END || ', '
      || CASE WHEN has_gallery THEN 'gallery' ELSE 'NULL' END || ', '
      || CASE WHEN has_award THEN 'award' ELSE 'NULL' END || ', '
      || CASE WHEN has_is_recommended THEN 'COALESCE(is_recommended, FALSE)' ELSE 'FALSE' END || ', '
      || CASE WHEN has_sort_order THEN 'COALESCE(sort_order, 0)' ELSE '0' END || ', '
      || CASE WHEN has_is_hidden THEN 'COALESCE(is_hidden, FALSE)' ELSE 'FALSE' END || ', created_at
      FROM public.projects WHERE category = ''Activity''
      ON CONFLICT DO NOTHING';

    -- Migrate Experiences
    EXECUTE 'INSERT INTO public.experiences (title, category, description, year, link_url, github_url, my_role, problem, solution, results_impact, key_learnings, tags, tools, features, languages, video_url, gallery, award, is_recommended, sort_order, is_hidden, created_at)
      SELECT title, ''Experience'', description, year, link_url, '
      || CASE WHEN has_github_url THEN 'github_url' ELSE 'NULL' END || ', '
      || CASE WHEN has_my_role THEN 'my_role' ELSE 'NULL' END || ', '
      || CASE WHEN has_problem THEN 'problem' ELSE 'NULL' END || ', '
      || CASE WHEN has_solution THEN 'solution' ELSE 'NULL' END || ', '
      || CASE WHEN has_results_impact THEN 'results_impact' ELSE 'NULL' END || ', '
      || CASE WHEN has_key_learnings THEN 'key_learnings' ELSE 'NULL' END || ', '
      || CASE WHEN has_tags THEN 'tags' ELSE 'NULL' END || ', '
      || CASE WHEN has_tools THEN 'tools' ELSE 'NULL' END || ', '
      || CASE WHEN has_features THEN 'features' ELSE 'NULL' END || ', '
      || CASE WHEN has_languages THEN 'languages' ELSE 'NULL' END || ', '
      || CASE WHEN has_video_url THEN 'video_url' ELSE 'NULL' END || ', '
      || CASE WHEN has_gallery THEN 'gallery' ELSE 'NULL' END || ', '
      || CASE WHEN has_award THEN 'award' ELSE 'NULL' END || ', '
      || CASE WHEN has_is_recommended THEN 'COALESCE(is_recommended, FALSE)' ELSE 'FALSE' END || ', '
      || CASE WHEN has_sort_order THEN 'COALESCE(sort_order, 0)' ELSE '0' END || ', '
      || CASE WHEN has_is_hidden THEN 'COALESCE(is_hidden, FALSE)' ELSE 'FALSE' END || ', created_at
      FROM public.projects WHERE category = ''Experience''
      ON CONFLICT DO NOTHING';

    -- Delete migrated rows from projects table
    DELETE FROM public.projects WHERE category IN ('Achievement', 'Activity', 'Experience');

    -- Remove image_icon column from projects table if it exists
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'image_icon') THEN
      ALTER TABLE public.projects DROP COLUMN image_icon;
    END IF;
  END IF;
END $$;

-- 5. Enable Row Level Security & Public Policies
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read achievements" ON public.achievements;
DROP POLICY IF EXISTS "Allow all achievements" ON public.achievements;
CREATE POLICY "Allow all achievements" ON public.achievements FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read activities" ON public.activities;
DROP POLICY IF EXISTS "Allow all activities" ON public.activities;
CREATE POLICY "Allow all activities" ON public.activities FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read experiences" ON public.experiences;
DROP POLICY IF EXISTS "Allow all experiences" ON public.experiences;
CREATE POLICY "Allow all experiences" ON public.experiences FOR ALL USING (true) WITH CHECK (true);

-- Ensure projects table and separated tables have all required columns
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN DEFAULT FALSE;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS my_role TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS problem TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS solution TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS results_impact TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS key_learnings TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS tools TEXT[];
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS features TEXT[];
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS languages JSONB;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS gallery TEXT[];
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS award JSONB;

ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN DEFAULT FALSE;

ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN DEFAULT FALSE;

ALTER TABLE public.experiences ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE public.experiences ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE public.experiences ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN DEFAULT FALSE;

-- 6. Update Stored Functions (RPCs) to remove image_icon references and drop all overloaded signatures
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN (
    SELECT proname, oid::regprocedure AS func_signature
    FROM pg_proc
    WHERE proname IN ('admin_insert_project', 'admin_update_project', 'admin_delete_project')
      AND pronamespace = 'public'::regnamespace
  ) LOOP
    EXECUTE 'DROP FUNCTION IF EXISTS ' || r.func_signature || ' CASCADE';
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.admin_insert_project(payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  new_id BIGINT;
BEGIN
  INSERT INTO public.projects (
    title, category, description, year, link_url, github_url,
    my_role, problem, solution, results_impact, key_learnings,
    tags, tools, features, languages, video_url, gallery, award,
    is_recommended, sort_order, is_hidden
  ) VALUES (
    payload->>'title',
    payload->>'category',
    payload->>'description',
    payload->>'year',
    payload->>'link_url',
    payload->>'github_url',
    payload->>'my_role',
    payload->>'problem',
    payload->>'solution',
    payload->>'results_impact',
    payload->>'key_learnings',
    ARRAY(SELECT jsonb_array_elements_text(payload->'tags')),
    ARRAY(SELECT jsonb_array_elements_text(payload->'tools')),
    ARRAY(SELECT jsonb_array_elements_text(payload->'features')),
    payload->'languages',
    payload->>'video_url',
    ARRAY(SELECT jsonb_array_elements_text(payload->'gallery')),
    payload->'award',
    COALESCE((payload->>'is_recommended')::boolean, false),
    COALESCE((payload->>'sort_order')::integer, 0),
    COALESCE((payload->>'is_hidden')::boolean, false)
  )
  RETURNING id INTO new_id;

  RETURN jsonb_build_object('id', new_id, 'status', 'success');
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_update_project(p_id BIGINT, payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.projects
  SET
    title = COALESCE(payload->>'title', title),
    category = COALESCE(payload->>'category', category),
    description = COALESCE(payload->>'description', description),
    year = COALESCE(payload->>'year', year),
    link_url = COALESCE(payload->>'link_url', link_url),
    github_url = COALESCE(payload->>'github_url', github_url),
    my_role = COALESCE(payload->>'my_role', my_role),
    problem = COALESCE(payload->>'problem', problem),
    solution = COALESCE(payload->>'solution', solution),
    results_impact = COALESCE(payload->>'results_impact', results_impact),
    key_learnings = COALESCE(payload->>'key_learnings', key_learnings),
    tags = CASE WHEN payload ? 'tags' THEN ARRAY(SELECT jsonb_array_elements_text(payload->'tags')) ELSE tags END,
    tools = CASE WHEN payload ? 'tools' THEN ARRAY(SELECT jsonb_array_elements_text(payload->'tools')) ELSE tools END,
    features = CASE WHEN payload ? 'features' THEN ARRAY(SELECT jsonb_array_elements_text(payload->'features')) ELSE features END,
    languages = CASE WHEN payload ? 'languages' THEN payload->'languages' ELSE languages END,
    video_url = COALESCE(payload->>'video_url', video_url),
    gallery = CASE WHEN payload ? 'gallery' THEN ARRAY(SELECT jsonb_array_elements_text(payload->'gallery')) ELSE gallery END,
    award = CASE WHEN payload ? 'award' THEN payload->'award' ELSE award END,
    is_recommended = COALESCE((payload->>'is_recommended')::boolean, is_recommended),
    sort_order = COALESCE((payload->>'sort_order')::integer, sort_order),
    is_hidden = COALESCE((payload->>'is_hidden')::boolean, is_hidden)
  WHERE id = p_id;

  RETURN jsonb_build_object('status', 'success');
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_project(p_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.projects WHERE id = p_id;
  RETURN jsonb_build_object('status', 'success');
END;
$$;


